export interface ImproveLink {
  label: string;
  href: string;
  reason: string;
}

const SECTION_ROUTES: Record<string, ImproveLink[]> = {
  '1.0': [{ label: 'Governance Dashboard', href: '/governance-engine', reason: 'Review overall governance structure' }],
  '1.1': [{ label: 'Governance Engine', href: '/governance-engine', reason: 'View purpose and scope' }],
  '1.2': [{ label: 'User Management', href: '/', reason: 'Configure authority and delegation' }],
  '1.3': [{ label: 'Governance Engine', href: '/governance-engine', reason: 'Operating model' }],
  '1.4': [{ label: 'Document Control', href: '/compliance', reason: 'Document hierarchy' }],
  '1.5': [{ label: 'Solicitation Review', href: '/governance-engine/solicitations', reason: 'Versioning and lock enforcement' }],
  '1.6': [{ label: 'Audit Trail', href: '/governance-engine/solicitations', reason: 'System-of-record' }],
  '2.0': [{ label: 'Maturity Index', href: '/governance-engine/maturity', reason: 'GCI scoring' }],
  '2.1': [{ label: 'Governance Maturity', href: '/governance-engine/maturity', reason: 'Governance Completeness Index' }],
  '2.2': [{ label: 'Maturity Pillars', href: '/governance-engine/maturity', reason: 'Pillar methodology' }],
  '2.3': [{ label: 'Auto-Builder', href: '/governance-engine/auto-builder', reason: 'Automation classification' }],
  '2.4': [{ label: 'Audit Trail', href: '/governance-engine/solicitations', reason: 'System telemetry' }],
  '2.5': [{ label: 'Maturity + Auto-Builder', href: '/governance-engine/auto-builder', reason: 'Improvement cycle' }],
  '3.0': [{ label: 'Clause Library', href: '/governance-engine/clause-library', reason: 'Clause risk governance' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'ClauseMaster >= 20 entries' }],
  '3.1': [{ label: 'Clause Library', href: '/compliance', reason: 'Clause library structure' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'ClauseMaster >= 20 entries' }],
  '3.2': [{ label: 'Risk Model Config', href: '/governance-engine/solicitations', reason: 'Risk classification' }],
  '3.3': [{ label: 'Solicitation Review', href: '/governance-engine/solicitations', reason: 'Weighting and thresholds' }],
  '3.4': [{ label: 'Solicitation Review', href: '/governance-engine/solicitations', reason: 'Escalation triggers' }],
  '3.5': [{ label: 'Clause Library', href: '/compliance', reason: 'Clause version control' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'ClauseMaster >= 20 entries' }],
  '3.6': [{ label: 'Clause Risk Log', href: '/governance-engine/solicitations', reason: 'Clause risk log' }],
  '4.0': [{ label: 'Solicitations', href: '/governance-engine/solicitations', reason: 'Pre-bid workflow' }],
  '4.1': [{ label: 'New Solicitation', href: '/governance-engine/solicitations/new', reason: 'Mandatory workflow' }],
  '4.2': [{ label: 'Approvals', href: '/governance-engine/solicitations', reason: 'Approval gating' }],
  '4.3': [{ label: 'Solicitation Review', href: '/governance-engine/solicitations', reason: 'Override protocol' }],
  '4.4': [{ label: 'Finalize', href: '/governance-engine/solicitations', reason: 'Finalization lock' }],
  '4.5': [{ label: 'Escalations', href: '/governance-engine/solicitations', reason: 'Executive escalation' }],
  '5.0': [{ label: 'Clause Library', href: '/compliance', reason: 'Flow-down governance' }],
  '5.1': [{ label: 'Clause Library', href: '/compliance', reason: 'Flow-down identification' }],
  '5.2': [{ label: 'Clause Library', href: '/compliance', reason: 'Conditional flow-down' }],
  '5.3': [{ label: 'Contracts', href: '/contracts', reason: 'Subcontract risk' }],
  '5.4': [{ label: 'Audit Trail', href: '/governance-engine/solicitations', reason: 'Flow-down audit' }],
  '6.0': [{ label: 'Financials', href: '/financials', reason: 'Cost accounting' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CostAccount dataset' }],
  '6.1': [{ label: 'Financials', href: '/financials', reason: 'Direct vs indirect' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CostAccount dataset' }],
  '6.2': [{ label: 'Financials', href: '/financials', reason: 'Cost pool definitions' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CostAccount dataset' }],
  '6.3': [{ label: 'Job Costs', href: '/financials', reason: 'Job cost traceability' }],
  '6.4': [{ label: 'Contracts', href: '/contracts', reason: 'Funding threshold' }],
  '6.5': [{ label: 'Contracts', href: '/contracts', reason: 'Change order controls' }],
  '7.0': [{ label: 'Financials', href: '/financials', reason: 'Indirect rates' }],
  '7.1': [{ label: 'Indirect Rates', href: '/financials', reason: 'Fringe, overhead, G&A' }],
  '7.2': [{ label: 'Financials', href: '/financials', reason: 'Allocation base' }],
  '7.3': [{ label: 'Financials', href: '/financials', reason: 'True-up' }],
  '7.4': [{ label: 'Financials', href: '/financials', reason: 'Provisional vs final' }],
  '8.0': [{ label: 'Financials', href: '/financials', reason: 'FAR compliance' }],
  '8.1': [{ label: 'Financials', href: '/financials', reason: 'FAR Part 31' }],
  '8.2': [{ label: 'Financials', href: '/financials', reason: 'Allowable controls' }],
  '8.3': [{ label: 'Audit Trail', href: '/governance-engine/solicitations', reason: 'Audit trail' }],
  '8.4': [{ label: 'Financials', href: '/financials', reason: 'DCAA readiness' }],
  '9.0': [{ label: 'Contracts', href: '/contracts', reason: 'Insurance standards' }],
  '9.1': [{ label: 'Contracts', href: '/contracts', reason: 'Baseline coverage' }],
  '9.2': [{ label: 'Contracts', href: '/contracts', reason: 'Contract scaling' }],
  '9.3': [{ label: 'Contracts', href: '/contracts', reason: 'Certificate tracking' }],
  '9.4': [{ label: 'Contracts', href: '/contracts', reason: 'Additional insured' }],
  '10.0': [{ label: 'Solicitation Review', href: '/governance-engine/solicitations', reason: 'Indemnification' }],
  '10.1': [{ label: 'Clause Review', href: '/governance-engine/solicitations', reason: 'Indemnification matrix' }],
  '10.2': [{ label: 'Risk Levels', href: '/governance-engine/solicitations', reason: 'Risk tier mapping' }],
  '10.3': [{ label: 'Escalations', href: '/governance-engine/solicitations', reason: 'Escalation doctrine' }],
  '10.4': [{ label: 'Contracts', href: '/contracts', reason: 'Risk transfer' }],
  '11.0': [{ label: 'Cyber', href: '/cyber', reason: 'CUI boundary' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110 entries' }],
  '11.1': [{ label: 'Cyber', href: '/cyber', reason: 'Segmentation' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '11.2': [{ label: 'Cyber', href: '/cyber', reason: 'RBAC' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '11.3': [{ label: 'Cyber', href: '/cyber', reason: 'MFA enforcement' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '11.4': [{ label: 'Cyber', href: '/cyber', reason: 'Data retention' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '12.0': [{ label: 'Cyber', href: '/cyber', reason: 'Incident response' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '12.1': [{ label: 'Cyber', href: '/cyber', reason: 'Detection' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '12.2': [{ label: 'Cyber', href: '/cyber', reason: '72-hour reporting' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '12.3': [{ label: 'Cyber', href: '/cyber', reason: 'Documentation' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '12.4': [{ label: 'Cyber', href: '/cyber', reason: 'Root cause' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '13.0': [{ label: 'Cyber', href: '/cyber', reason: 'CMMC alignment' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '13.1': [{ label: 'Cyber', href: '/cyber', reason: 'Control mapping' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '13.2': [{ label: 'Cyber', href: '/cyber', reason: 'Control ownership' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '13.3': [{ label: 'Cyber', href: '/cyber', reason: 'Monitoring' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '13.4': [{ label: 'Cyber', href: '/cyber', reason: 'POA&M' }, { label: 'Import Dataset', href: '/admin/compliance-registry', reason: 'CyberControlMaster >= 110' }],
  '14.0': [{ label: 'Contracts', href: '/contracts', reason: 'REA & claims' }],
  '14.1': [{ label: 'Contracts', href: '/contracts', reason: 'REA calculation' }],
  '14.2': [{ label: 'Contracts', href: '/contracts', reason: 'Claims indexing' }],
  '14.3': [{ label: 'Contracts', href: '/contracts', reason: 'Termination' }],
  '14.4': [{ label: 'Contracts', href: '/contracts', reason: 'Change orders' }],
  '15.0': [{ label: 'Contracts', href: '/contracts', reason: 'Ownership' }],
  '15.1': [{ label: 'Contracts', href: '/contracts', reason: 'SDVOSB' }],
  '15.2': [{ label: 'Contracts', href: '/contracts', reason: 'Affiliation' }],
  '15.3': [{ label: 'Contracts', href: '/contracts', reason: 'Control matrix' }],
  '15.4': [{ label: 'Contracts', href: '/contracts', reason: 'Negative control' }],
  '16.0': [{ label: 'Maturity + Audit', href: '/governance-engine/maturity', reason: 'Audit framework' }],
  '16.1': [{ label: 'Reports', href: '/governance-engine/reports', reason: 'Audit scope' }],
  '16.2': [{ label: 'Maturity', href: '/governance-engine/maturity', reason: 'KPI oversight' }],
  '16.3': [{ label: 'Auto-Builder', href: '/governance-engine/auto-builder', reason: 'Corrective action' }],
  '16.4': [{ label: 'Maturity', href: '/governance-engine/maturity', reason: 'Certification' }]
};

const SECTION_PILLARS: Record<string, string[]> = {
  '1.0': ['Structural'], '1.1': ['Structural'], '1.2': ['Structural'], '1.3': ['Structural'], '1.4': ['Documentation'], '1.5': ['Contract'], '1.6': ['Audit'],
  '2.0': ['Audit'], '2.1': ['Audit'], '2.2': ['Audit'], '2.3': ['Audit'], '2.4': ['Audit'], '2.5': ['Audit'],
  '3.0': ['Contract'], '3.1': ['Contract'], '3.2': ['Contract'], '3.3': ['Contract'], '3.4': ['Contract'], '3.5': ['Contract'], '3.6': ['Contract'],
  '4.0': ['Contract', 'Audit'], '4.1': ['Contract'], '4.2': ['Audit'], '4.3': ['Audit'], '4.4': ['Contract'], '4.5': ['Contract'],
  '5.0': ['Contract'], '5.1': ['Contract'], '5.2': ['Contract'], '5.3': ['Contract'], '5.4': ['Audit'],
  '6.0': ['Financial'], '6.1': ['Financial'], '6.2': ['Financial'], '6.3': ['Financial'], '6.4': ['Financial'], '6.5': ['Financial'],
  '7.0': ['Financial'], '7.1': ['Financial'], '7.2': ['Financial'], '7.3': ['Financial'], '7.4': ['Financial'],
  '8.0': ['Financial', 'Audit'], '8.1': ['Financial'], '8.2': ['Financial'], '8.3': ['Audit'], '8.4': ['Audit'],
  '9.0': ['Insurance'], '9.1': ['Insurance'], '9.2': ['Insurance'], '9.3': ['Insurance'], '9.4': ['Insurance'],
  '10.0': ['Insurance', 'Contract'], '10.1': ['Insurance'], '10.2': ['Contract'], '10.3': ['Contract'], '10.4': ['Insurance'],
  '11.0': ['Cyber'], '11.1': ['Cyber'], '11.2': ['Cyber'], '11.3': ['Cyber'], '11.4': ['Cyber'],
  '12.0': ['Cyber'], '12.1': ['Cyber'], '12.2': ['Cyber'], '12.3': ['Cyber'], '12.4': ['Cyber'],
  '13.0': ['Cyber'], '13.1': ['Cyber'], '13.2': ['Cyber'], '13.3': ['Cyber'], '13.4': ['Cyber'],
  '14.0': ['Financial'], '14.1': ['Financial'], '14.2': ['Documentation'], '14.3': ['Financial'], '14.4': ['Financial'],
  '15.0': ['Structural'], '15.1': ['Structural'], '15.2': ['Structural'], '15.3': ['Structural'], '15.4': ['Structural'],
  '16.0': ['Audit'], '16.1': ['Audit'], '16.2': ['Audit'], '16.3': ['Audit'], '16.4': ['Audit']
};

export function getImproveLinks(sectionId: string): ImproveLink[] {
  return SECTION_ROUTES[sectionId] ?? [{ label: 'Governance Engine', href: '/governance-engine', reason: 'Review governance modules' }];
}

export function getPillarsForSection(sectionId: string): string[] {
  return SECTION_PILLARS[sectionId] ?? ['Contract'];
}
